import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Providers from "@/components/tw/Providers";
import { Toaster } from "sonner";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Affaldsguiden",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Providers>
          <Navbar />
          <div className="min-h-[calc(100vh-80.69px-64px)] relative">
            <div className="bg-gradient-to-b from-[#62BB6533] to-transparent h-[80vh] absolute w-full -z-10 top-0 left-0" />
            {children}
          </div>
          <Toaster richColors />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
